### ISSUE TITLE
Grameenphone APN issue

### ISSUE THREAD

**Issue by Apon77** [crdroidandroid/android_vendor_crdroid#36]
https://github.com/crdroidandroid/android_vendor_crdroid/blob/4b2b71e7647bae072ef255026ecaac9640f26339/prebuilt/common/etc/apns-conf.xml#L3181

APN should be 'gpinternet' not 'gpinterneth'

**Comment by xNombre** [comment]
Can you PR?

**Comment by Apon77** [comment]
> Can you PR?

Done, https://github.com/crdroidandroid/android_vendor_crdroid/pull/38
