### ISSUE TITLE
"Make lineage great again" broke clang prebuilt paths

### ISSUE THREAD

**Issue by Terminator-J** [crdroidandroid/android_vendor_crdroid#4]
So, does anyone else trying to build 10.0 have the problem that the kernel won't compile without manually fudging the prebuilt clang binary paths or symlinking or copying clang/clang++/clang.real/clang++.real up one level? Because right now I sure do trying to build for enchilada/fajita. 
Looks like in commit 3ca219fc0ae55b17e27b3bc3cbdfb90333cc2fc7, the change to build/tasks/kernel.mk on line 174...
KBUILD_COMPILER_STRING := $(shell $(TARGET_KERNEL_CLANG_PATH)/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')
... is trying to run the clang binary with --version to munge the output and export the variable "KBUILD_COMPILER_STRING". However, it only tries to execute clang in "$(TARGET_KERNEL_CLANG_PATH)", which doesn't have any executable binaries in it, instead of the subdirectory "$(TARGET_KERNEL_CLANG_PATH)/bin" which has all the executable binaries in it. SO, trying to just build will continually result in a warning about clang not being found in the path while ninja is getting its stuff together, and then about 30% of the way through building, it'll error out because clang wasn't found when it came time to finally build the kernel. 
For a proposed fix, please see https://github.com/Terminator-J/android_vendor_crdroid/commit/ab3580f302cef29679bf23bbfacbf80d6b4f7489

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_vendor_crdroid/commit/ad6716ff7392fdb5ddbfa78314169bc4d342fff3
